<nav class="space-y-1 text-sm">
    <a href="{{ route('portal.dashboard') }}" class="block px-3 py-2 rounded-lg {{ request()->routeIs('portal.dashboard') ? 'bg-indigo-600 text-white' : 'text-gray-600 hover:bg-gray-100' }}"><x-icon name="chart-bar" class="w-4 h-4 inline-block" /> Dashboard</a>
    <a href="{{ route('portal.projects') }}" class="block px-3 py-2 rounded-lg {{ request()->routeIs('portal.projects*') ? 'bg-indigo-600 text-white' : 'text-gray-600 hover:bg-gray-100' }}"><x-icon name="folder" class="w-4 h-4 inline-block" /> Projects</a>
    <a href="{{ route('portal.reports') }}" class="block px-3 py-2 rounded-lg {{ request()->routeIs('portal.reports*') ? 'bg-indigo-600 text-white' : 'text-gray-600 hover:bg-gray-100' }}"><x-icon name="chart-bar" class="w-4 h-4 inline-block" /> Reports</a>
    <a href="{{ route('portal.approvals') }}" class="block px-3 py-2 rounded-lg {{ request()->routeIs('portal.approvals') ? 'bg-indigo-600 text-white' : 'text-gray-600 hover:bg-gray-100' }}"><x-icon name="check-circle" class="w-4 h-4 inline-block" /> Approvals</a>
    <a href="{{ route('portal.requests') }}" class="block px-3 py-2 rounded-lg {{ request()->routeIs('portal.requests*') ? 'bg-indigo-600 text-white' : 'text-gray-600 hover:bg-gray-100' }}"><x-icon name="envelope" class="w-4 h-4 inline-block" /> Requests</a>
    <a href="{{ route('portal.invoices') }}" class="block px-3 py-2 rounded-lg {{ request()->routeIs('portal.invoices*') ? 'bg-indigo-600 text-white' : 'text-gray-600 hover:bg-gray-100' }}"><x-icon name="receipt" class="w-4 h-4 inline-block" /> Invoices</a>
    <a href="{{ route('portal.files') }}" class="block px-3 py-2 rounded-lg {{ request()->routeIs('portal.files*') ? 'bg-indigo-600 text-white' : 'text-gray-600 hover:bg-gray-100' }}"><x-icon name="paper-clip" class="w-4 h-4 inline-block" /> Files</a>
</nav>
