<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $report->title }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #111827; }
        .header { display: flex; justify-content: space-between; align-items: center; border-bottom: 3px solid #4f46e5; padding-bottom: 12px; margin-bottom: 20px; }
        .logo { font-size: 20px; font-weight: 900; }
        .logo span { color: #4f46e5; }
        .client { text-align: right; font-size: 13px; font-weight: 700; }
        .period { color: #6b7280; font-size: 10px; margin-top: 3px; }
        h2 { font-size: 14px; color: #4f46e5; margin: 24px 0 10px; border-bottom: 1px solid #e5e7eb; padding-bottom: 5px; }
        table { width: 100%; border-collapse: collapse; margin: 8px 0; }
        th { background: #f3f4f6; text-align: left; padding: 7px; font-size: 10px; text-transform: uppercase; }
        td { padding: 7px; border-bottom: 1px solid #e5e7eb; }
        .metric-row td:first-child { color: #4b5563; }
        .commentary { margin-top: 16px; padding: 10px 12px; background: #f9fafb; border-left: 3px solid #10b981; }
        .commentary h3 { font-size: 12px; margin: 0 0 4px; }
        .commentary p { margin: 0; color: #4b5563; }
        .footer { margin-top: 30px; text-align: center; font-size: 9px; color: #9ca3af; border-top: 1px solid #e5e7eb; padding-top: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <div>
            <div class="logo">Agency<span>OS</span> — {{ $tenant?->name ?? config('app.name') }}</div>
            <div class="period">{{ ucfirst($report->report_type) }} report · {{ $report->period_start->format('d M Y') }} – {{ $report->period_end->format('d M Y') }}</div>
        </div>
        <div>
            <div class="client">{{ $report->client->company_name }}</div>
            <div class="period">Prepared {{ $report->created_at->format('d M Y') }}</div>
        </div>
    </div>

    <h2>Executive Summary</h2>
    <p>{{ $report->title }}</p>
    @if ($report->insights)
        <p><strong>What worked:</strong> {{ $report->insights }}</p>
    @endif

    @foreach (($report->data['sections'] ?? []) as $key => $section)
        <h2>{{ ['paid_advertising' => 'Paid Advertising', 'shopify' => 'Shopify', 'social_media' => 'Social Media', 'website' => 'Website'][$key] ?? ucwords(str_replace('_', ' ', $key)) }}</h2>
        <table>
            <thead><tr><th>Metric</th><th style="text-align:right">Value</th></tr></thead>
            <tbody>
                @foreach ($section as $metric => $value)
                    <tr class="metric-row">
                        <td>{{ ucwords(str_replace('_', ' ', $metric)) }}</td>
                        <td style="text-align:right; font-weight:600">{{ number_format((float) $value, 2) }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endforeach

    @if ($report->recommendations)
        <div class="commentary"><h3>🔧 Areas to improve</h3><p>{{ $report->recommendations }}</p></div>
    @endif
    @if ($report->next_priorities)
        <div class="commentary"><h3>🎯 Next priorities</h3><p>{{ $report->next_priorities }}</p></div>
    @endif

    <div class="footer">Generated by Agency OS · {{ $tenant?->name ?? config('app.name') }} · {{ now()->format('d M Y H:i') }}</div>
</body>
</html>
