<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $proposal->proposal_number }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #111827; }
        .header { display: flex; justify-content: space-between; margin-bottom: 30px; }
        .logo { font-size: 22px; font-weight: 900; }
        .logo span { color: #4f46e5; }
        h1 { font-size: 20px; margin: 0 0 4px; }
        .meta { color: #6b7280; font-size: 11px; }
        table.items { width: 100%; border-collapse: collapse; margin-top: 20px; }
        table.items th { background: #f3f4f6; text-align: left; padding: 8px; font-size: 11px; text-transform: uppercase; }
        table.items td { padding: 8px; border-bottom: 1px solid #e5e7eb; }
        .totals { margin-left: auto; width: 280px; margin-top: 20px; }
        .totals div { display: flex; justify-content: space-between; padding: 3px 0; }
        .totals .grand { font-weight: 900; font-size: 14px; border-top: 2px solid #111827; margin-top: 5px; padding-top: 8px; }
        .notes { margin-top: 24px; font-size: 11px; color: #4b5563; }
        .footer { margin-top: 40px; font-size: 10px; color: #9ca3af; text-align: center; border-top: 1px solid #e5e7eb; padding-top: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <div>
            <div class="logo">Task<span>365</span> — {{ $proposal->tenant?->name ?? config('app.name') }}</div>
            <div class="meta">{{ $proposal->tenant?->email ?? '' }}</div>
        </div>
        <div style="text-align: right">
            <h1>PROPOSAL</h1>
            <div class="meta">#{{ $proposal->proposal_number }}</div>
            <div class="meta">Valid until: {{ $proposal->valid_until?->format('d M Y') ?? '—' }}</div>
            <div style="margin-top:8px; font-weight:600">{{ $proposal->client->company_name }}</div>
            <div class="meta">{{ $proposal->client->address }}</div>
        </div>
    </div>

    <h2 style="font-size:14px">{{ $proposal->title }}</h2>

    <table class="items">
        <thead><tr><th>Service</th><th style="text-align:right">Qty</th><th style="text-align:right">Rate</th><th style="text-align:right">Amount</th></tr></thead>
        <tbody>
            @foreach ($proposal->items as $item)
                <tr>
                    <td>{{ $item->description }}</td>
                    <td style="text-align:right">{{ $item->quantity }}</td>
                    <td style="text-align:right">{{ number_format($item->unit_price, 2) }}</td>
                    <td style="text-align:right">{{ number_format($item->total, 2) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="totals">
        <div><span>Subtotal</span><span>{{ number_format($proposal->subtotal, 2) }}</span></div>
        @if ($proposal->discount_amount > 0)
            <div><span>Discount</span><span>-{{ number_format($proposal->discount_amount, 2) }}</span></div>
        @endif
        <div><span>Tax ({{ $proposal->tax_rate }}%)</span><span>{{ number_format($proposal->tax_amount, 2) }}</span></div>
        <div class="grand"><span>Total ({{ $proposal->currency }})</span><span>{{ number_format($proposal->total_amount, 2) }}</span></div>
    </div>

    @if ($proposal->notes)<div class="notes"><strong>Notes:</strong> {{ $proposal->notes }}</div>@endif
    @if ($proposal->terms)<div class="notes"><strong>Terms:</strong> {{ $proposal->terms }}</div>@endif

    <div class="footer">Generated by Task365 · {{ now()->format('d M Y') }}</div>
</body>
</html>
